name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.2
    - run: export PATH=$HOME/.yarn/bin:$PATH
    - run: yarn
    - run: yarn lint
    - shell: bash
      env:
        GEO_APP_ID: ${{ secrets.GEO_APP_ID }}
        GEO_APP_KEY: ${{ secrets.GEO_APP_KEY }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        PARSE_APP_ID: ${{ secrets.PARSE_APP_ID }}
        PARSE_JAVASCRIPT_KEY: ${{ secrets.PARSE_JAVASCRIPT_KEY }}
        PARSE_MASTER_KEY: ${{ secrets.PARSE_MASTER_KEY }}
        PARSE_SERVER_URL: ${{ secrets.PARSE_SERVER_URL }}
      run: yarn test
    - run: yarn build --release
      env:
        CI: true
    - run: yarn serve & sleep 1
    - run: curl --fail -D- localhost:3000/api/categories
